#pragma once

#define PROTOTYPE_CPP_MODULES_VERSION_MAJOR    0
#define PROTOTYPE_CPP_MODULES_VERSION_MINOR    0
#define PROTOTYPE_CPP_MODULES_VERSION_PATCH    1
#define PROTOTYPE_CPP_MODULES_VERSION_BUILD    24070
#define PROTOTYPE_CPP_MODULES_VERSION_COMMA    0,0,1

#define PROTOTYPE_CPP_MODULES_VERSION          "0.0.1.24070"
